### ISSUE TITLE
Exception in This Project

### ISSUE THREAD

**Issue by shadikkhan** [Remchi/crud-with-redux#2]
I tried to run it after download and setup but I get the exception as in attached image

![image](https://cloud.githubusercontent.com/assets/16745242/22816053/970150dc-ef85-11e6-928f-76b5b382baf8.png)

Got this issue in video no 2, When setting up Link from react-router.
Does it need webpack setting too?

**Comment by ouss4m4** [comment]
it's all about the react-router,
rem pushed to master a fix , it work now (i also just started followin the serie)

good luck

**Comment by shadikkhan** [comment]
Thank you @Remchi and @ouss4m4
